export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  payoneerEmail: process.env.PAYONEER_EMAIL ?? "",
  paypalEmail: process.env.PAYPAL_EMAIL ?? "",
  paypalMerchantId: process.env.PAYPAL_MERCHANT_ID ?? "",
  bkashNumber: process.env.BKASH_NUMBER ?? "",
  nagadNumber: process.env.NAGAD_NUMBER ?? "",
  rocketNumber: process.env.ROCKET_NUMBER ?? "",
  binanceId: process.env.BINANCE_ID ?? "",
};
